version: "3.9"
services:
  client:
    build:
      context: ./json-client
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./json-config/client.env
    volumes:
      - ./json-client/src:/home/app/src
      - /home/app/src/node_modules
    networks:
      - net-json-transformer

  api:
    build:
      context: ./json-api
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./json-config/api.env
    volumes:
      - ./json-api/src:/home/app/src
    networks:
      - net-json-transformer

networks:
  net-json-transformer:
    name: net-json-transformer
